const pageTitles={home:'早上好，周末 <span>☀️</span>',ledger:'家庭账本',calendar:'共享日历',chores:'家务管理',plans:'项目规划',links:'链接收藏库',moments:'家庭时光',fun:'趣味空间',settings:'成员与设置'};
const modal=document.getElementById('modal');
function toast(message){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.append(el)}el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
function go(page){document.querySelector('.nav-item.active')?.classList.remove('active');document.querySelector(`.nav-item[data-page="${page}"]`)?.classList.add('active');document.querySelector('.page.active')?.classList.remove('active');document.getElementById(page)?.classList.add('active');document.getElementById('page-title').innerHTML=pageTitles[page]||'小家';window.location.hash=page==='home'?'':page}
function openModal(intent='内容'){modal.querySelector('h2').textContent=`新建${intent}`;modal.querySelector('p').textContent='选择一种类型，马上添加到家庭空间';modal.classList.add('open')}
document.querySelectorAll('.nav-item[data-page]').forEach(btn=>btn.addEventListener('click',()=>go(btn.dataset.page)));
document.querySelectorAll('.new-btn').forEach(btn=>btn.addEventListener('click',()=>openModal(btn.textContent.replace(/[＋+]/g,'').trim()||'内容')));
document.querySelector('.close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
function bindChore(label){const box=label.querySelector('input');if(!box)return;box.addEventListener('change',()=>{label.classList.toggle('completed',box.checked);toast(box.checked?'已完成，辛苦啦 ✨':'已重新放回待办')})}
function addChore(name){const label=document.createElement('label');label.innerHTML=`<input type="checkbox"><span class="check"></span><span>${name}</span><em class="avatar tiny blue">周</em>`;document.querySelector('#home .chore-list')?.append(label);bindChore(label);const board=document.querySelector('#chores .board-col');if(board){const item=document.createElement('article');item.textContent=name;board.append(item)}}
document.querySelectorAll('.chore-list label').forEach(bindChore);document.querySelector('.add-row')?.addEventListener('click',()=>{addChore('新增家务 · 待安排');toast('已添加一项新家务')});
function addPlan(name){const card=document.createElement('article');card.className='project-large travel';card.innerHTML=`<span>✨</span><div><small>刚刚创建 · 0%</small><h2>${name}</h2><p>0 个待办 · 点击开始规划</p></div>`;card.onclick=()=>{card.querySelector('small').textContent='进行中 · 10%';card.querySelector('p').textContent='已建立第一个待办 · 点击继续完善';toast('计划已开始推进')};document.querySelector('#plans .project-list')?.append(card)}
document.querySelector('.add-plan')?.addEventListener('click',()=>{addPlan('新的家庭计划');go('plans');toast('已创建新的家庭计划')});
document.querySelectorAll('.modal-options button').forEach(btn=>btn.addEventListener('click',()=>{const kind=btn.textContent.trim();modal.classList.remove('open');if(kind.includes('家务')){addChore('新家务事项');go('chores')}else if(kind.includes('计划')){addPlan('新的家庭计划');go('plans')}else if(kind.includes('日程')){const day=document.querySelector('.dates .selected');if(day&&!day.querySelector('i'))day.innerHTML+='<i>新日程</i>';go('calendar')}else if(kind.includes('动态')){document.querySelector('#moments .post-big h3').textContent='新的家庭动态正在等你记录。 ✨';go('moments')}toast(`已创建${kind}，可继续编辑`)}));
document.querySelectorAll('.dates span').forEach(day=>day.addEventListener('click',()=>{document.querySelector('.dates .selected')?.classList.remove('selected');day.classList.add('selected');toast(`已选择 9 月 ${day.childNodes[0].textContent.trim()} 日`)}));
document.querySelector('.wish-wall button')?.addEventListener('click',()=>{document.querySelector('.wish-wall h2').textContent='周末一起做一顿丰盛的早餐';toast('新的家庭心愿已点亮 ✦')});
document.querySelectorAll('.fun-grid button').forEach(btn=>btn.addEventListener('click',()=>{const title=btn.closest('article').querySelector('h3').textContent;btn.textContent=title==='家庭小游戏'?'房间已创建':'已打开';btn.classList.add('selected-action');toast(title==='家庭小游戏'?'游戏房间已创建，邀请家人加入吧！':`${title}已为你打开`)}));
document.querySelectorAll('.link-grid article').forEach(card=>card.addEventListener('click',()=>{card.classList.toggle('saved');toast(card.classList.contains('saved')?'已置顶收藏':'已取消置顶')}));
document.querySelectorAll('.members em').forEach(tag=>tag.addEventListener('click',()=>{tag.textContent=tag.textContent==='全部权限'?'基础权限':'全部权限';toast('成员权限已更新')}));
document.querySelectorAll('.text-btn').forEach(btn=>btn.addEventListener('click',()=>{const text=btn.textContent;if(text.includes('日历'))go('calendar');else if(text.includes('计划'))go('plans');else if(text.includes('明细'))go('ledger');else if(text.includes('看看'))go('moments')}));
const initial=window.location.hash.slice(1);if(initial&&pageTitles[initial])go(initial);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));

/* Persistent local app actions */
const appData=JSON.parse(localStorage.getItem('xiaojia-data')||'{"members":[{"name":"周末","role":"管理员 · 爸爸","permission":"全部权限"},{"name":"林晓","role":"管理员 · 妈妈","permission":"全部权限"},{"name":"小满","role":"成员 · 女儿","permission":"基础权限"}],"points":128}');
function saveData(){localStorage.setItem('xiaojia-data',JSON.stringify(appData))}
function formDialog(title,fields,onSubmit){modal.classList.remove('open');const overlay=document.createElement('div');overlay.className='form-overlay';overlay.innerHTML=`<form class="form-dialog"><button type="button" class="form-close">×</button><h2>${title}</h2>${fields.map(field=>`<label>${field.label}<input name="${field.name}" value="${field.value||''}" placeholder="${field.placeholder||''}" ${field.required?'required':''}></label>`).join('')}<button class="form-submit">保存</button></form>`;document.body.append(overlay);overlay.querySelector('.form-close').onclick=()=>overlay.remove();overlay.onclick=e=>{if(e.target===overlay)overlay.remove()};overlay.querySelector('form').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));onSubmit(values);overlay.remove()};overlay.querySelector('input')?.focus()}
function renderMembers(){const panel=document.querySelector('.members');if(!panel)return;panel.innerHTML=appData.members.map((member,index)=>`<div data-member="${index}"><span class="avatar ${index===1?'peach':index===2?'yellow':'blue'}">${member.name.slice(0,1)}</span><b>${member.name}</b><small>${member.role}</small><em>${member.permission}</em></div>`).join('');panel.querySelectorAll('div[data-member]').forEach(row=>row.onclick=()=>editMember(Number(row.dataset.member)))}
function editMember(index){const member=appData.members[index];formDialog('编辑家庭成员资料',[{label:'昵称',name:'name',value:member.name,required:true},{label:'身份说明',name:'role',value:member.role,required:true},{label:'权限（全部权限 / 基础权限）',name:'permission',value:member.permission,required:true}],values=>{appData.members[index]=values;saveData();renderMembers();toast('成员资料已保存')})}
renderMembers();
document.querySelector('#settings .new-btn')?.addEventListener('click',()=>formDialog('邀请家庭成员',[{label:'昵称',name:'name',placeholder:'例如：乐乐',required:true},{label:'身份说明',name:'role',placeholder:'例如：成员 · 儿子',required:true},{label:'权限',name:'permission',value:'基础权限',required:true}],values=>{appData.members.push(values);saveData();renderMembers();toast('新成员已加入小家')}));
document.querySelector('#ledger .new-btn')?.addEventListener('click',()=>formDialog('记录一笔账',[{label:'项目名称',name:'name',placeholder:'例如：超市采购',required:true},{label:'金额（元）',name:'amount',placeholder:'例如：128.00',required:true},{label:'分类',name:'category',value:'日常生活',required:true}],values=>{const row=document.createElement('div');row.className='record';row.innerHTML=`<span class="record-icon">✦</span><div><b>${values.name}</b><small>刚刚 · 周末</small></div><em>${values.category}</em><strong>- ¥ ${Number(values.amount).toFixed(2)}</strong>`;document.querySelector('#ledger .table-card').append(row);toast('账目已保存')}));
document.querySelector('#links .new-btn')?.addEventListener('click',()=>formDialog('收藏一个链接',[{label:'标题',name:'title',placeholder:'例如：京都旅行指南',required:true},{label:'分类',name:'category',placeholder:'例如：旅行',required:true}],values=>{const card=document.createElement('article');card.innerHTML=`<span>🔗</span><b>${values.title}</b><small>${values.category} · 刚刚收藏</small>`;card.onclick=()=>{card.classList.toggle('saved');toast(card.classList.contains('saved')?'已置顶收藏':'已取消置顶')};document.querySelector('.link-grid').prepend(card);toast('链接已收藏')}));
document.querySelector('#moments .new-btn')?.addEventListener('click',()=>formDialog('发布家庭动态',[{label:'想分享什么？',name:'content',placeholder:'记录今天的小事…',required:true}],values=>{document.querySelector('#moments .post-big h3').textContent=`“${values.content}”`;toast('家庭动态已发布')}));
document.querySelector('#calendar .new-btn')?.addEventListener('click',()=>formDialog('添加共享日程',[{label:'日程名称',name:'name',placeholder:'例如：家庭晚餐',required:true},{label:'日期',name:'date',value:'9 月 16 日',required:true}],values=>{const day=document.querySelector('.dates .selected');if(day)day.innerHTML=`${day.childNodes[0].textContent.trim()}<i>${values.name}</i>`;toast(`已将「${values.name}」加入${values.date}`)}));
document.querySelector('#chores .new-btn')?.addEventListener('click',()=>formDialog('添加家务',[{label:'家务事项',name:'name',placeholder:'例如：收拾餐桌',required:true}],values=>{addChore(values.name);toast('家务已添加')}));
document.querySelector('#plans .new-btn')?.addEventListener('click',()=>formDialog('新建家庭计划',[{label:'计划名称',name:'name',placeholder:'例如：春节回家计划',required:true}],values=>{addPlan(values.name);toast('计划已创建')}));
document.querySelector('#fun .new-btn')?.addEventListener('click',()=>formDialog('创建游戏房间',[{label:'房间名称',name:'name',placeholder:'例如：周末谁是卧底',required:true}],values=>{const card=document.querySelector('.fun-grid article');card.querySelector('h3').textContent=values.name;card.querySelector('p').textContent='等待家人加入 · 你是房主';card.querySelector('button').textContent='邀请家人';toast('游戏房间已创建')}));
document.querySelectorAll('#fun .fun-grid article').forEach((card,index)=>card.addEventListener('dblclick',()=>{if(index===1){appData.points=Math.max(0,appData.points-20);saveData();toast(`兑换成功，剩余 ${appData.points} 积分`)}else if(index===2)toast('抽签结果：今晚由林晓选择电影 🎬')}));
